apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ops-journal

spec:
  ingressClassName: nginx
  rules:
    - host: opsjournal-staging.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ops-journal
                port:
                  number: 80

